### PR TITLE
SDFat mag_field support

### PR DESCRIPTION
**Pull request by alvaro-oliver**
mag_field write and read support added for SDFat.
Example sketches updated.

### CODE REVIEW

**Comment by alvaro-oliver** [comment]
Related to issue #8: https://github.com/adafruit/Adafruit_Sensor_Calibration/issues/8

**Comment by ladyada** [comment]
hiya - what hardware did you test this change with :)

**Comment by alvaro-oliver** [comment]
> hiya - what hardware did you test this change with :)

Adafruit Feather nRF52840 Express + Adafruit LSM6DSOX + LIS3MDL FeatherWing, using Arduino Framework on PlatformIO.

**Comment by ladyada** [comment]
thanks :)

**Comment by alvaro-oliver** [comment]
thank you for encouraging me, this was my very first PR.
regards

**Comment by ladyada** [comment]
you did great!

**Pull request merged**
